from setuptools import setup, find_packages

with open('README.md', 'r', encoding='utf-8') as file:
    long_description = file.read()

setup(
    name='solarkat',  
    version='1.0.3', 
    author='Victória Samboco',
    author_email='vicky.samboco@gmail.com', 
    description='Solar imaging pipeline for solar interference mitigation in MeerkAT', 
    repository='https://github.com/ratt-ru/solarkat.git',  
    documentation = 'https://solarkat-docs.readthedocs.io/en/latest/',
    packages=find_packages(),
    long_description=long_description,
    long_description_content_type='text/markdown',
    install_requires=[
        'aiobotocore==2.11.1',
        'aiohttp==3.9.3',
        'aioitertools==0.10.0',
        'aiosignal==1.2.0',
        'antlr4-python3-runtime==4.9.3',
        'appdirs==1.4.4',
        'asciitree==0.3.3',
        'astLib==0.11.10',
        'astro-kittens==1.4.6',
        'astro-tigger-lsm==1.7.2',
        'astropy==5.1',
        'async-timeout==4.0.2',
        'attrs==22.1.0',
        'bokeh==2.4.3',
        'botocore==1.27.59',
        'breizorro==0.1.0',
        'certifi==2022.9.24',
        'charset-normalizer==2.1.1',
        'cli-ui==0.17.2',
        'click==8.1.3',
        'cloudpickle==2.2.0',
        'codex-africanus==0.3.3',
        'colorama==0.4.5',
        'Columnar==1.4.1',
        'commonmark==0.9.1',
        'configparser==5.3.0',
        'contextlib2==21.6.0',
        'contourpy==1.0.5',
        'cycler==0.11.0',
        'dask==2022.9.2',
        'dask-ms==0.2.14',
        'decorator==5.1.1',
        'dill==0.3.5.1',
        'distributed==2022.9.2',
        'docopt==0.6.2',
        'donfig==0.7.0',
        'entrypoints==0.4',
        'fasteners==0.18',
        'fonttools==4.38.0',
        'frozenlist==1.3.1',
        'fsspec==2022.8.2',
        'future==0.18.2',
        'future-fstrings==1.2.0',
        'HeapDict==1.0.1',
        'idna==3.4',
        'importlib-metadata==5.0.0',
        'iniconfig==1.1.1',
        'Jinja2==3.1.2',
        'jmespath==1.0.1',
        'kiwisolver==1.4.4',
        'llvmlite==0.39.1',
        'locket==1.0.0',
        'loguru==0.6.0',
        'MarkupSafe==2.1.1',
        'matplotlib==3.6.1',
        'msgpack==1.0.4',
        'msutils==1.2.0',
        'multidict==6.0.2',
        'multiprocess==0.70.13',
        'munch==2.5.0',
        'nose==1.3.7',
        'numba==0.56.2',
        'numcodecs==0.10.2',
        'numpy==1.23.3',
        'omegaconf==2.2.3',
        'packaging==21.3',
        'pandas==1.5.0',
        'partd==1.3.0',
        'pathos==0.2.9',
        'Pillow==9.2.0',
        'pkg_resources==0.0.0',
        'pluggy==1.0.0',
        'pox==0.3.1',
        'ppft==1.7.6.5',
        'psutil==5.9.2',
        'py==1.11.0',
        'pydantic==1.10.2',
        'pyerfa==2.0.0.1',
        'Pygments==2.13.0',
        'pyparsing==3.0.9',
        'pytest==7.1.3',
        'python-casacore==3.5.2',
        'python-dateutil==2.8.2',
        'pytz==2022.4',
        'PyYAML==6.0.1',
        'quartical==0.2.1',
        'regions>=0.5',
        'requests==2.28.1',
        'rich==12.5.1',
        'ruamel.yaml==0.17.21',
        'ruamel.yaml.clib==0.2.6',
        's3fs==2022.8.2',
        'scabha==2.0.0',
        'schema==0.7.5',
        'scipy==1.9.1',
        'six==1.16.0',
        'sortedcontainers==2.4.0',
        'stimela2==2.0rc4',
        'tabulate==0.8.10',
        'tblib==1.7.0',
        'tbump==6.9.0',
        'tomli==2.0.1',
        'tomlkit==0.11.5',
        'toolz==0.12.0',
        'tornado==6.1',
        'typing_extensions==4.3.0',
        'Unidecode==1.3.6',
        'urllib3==1.26.12',
        'wcwidth==0.2.5',
        'wrapt==1.14.1',
        'xarray==2022.9.0',
        'yarl==1.8.1',
        'zarr==2.13.2',
        'zict==2.2.0',
        'zipp==3.8.1',
        'breizoirro==0.1.2',
    ],

    classifiers=[ 
        'Development Status :: 4 - Beta', 
        'Intended Audience :: Science/Research',  
        'License :: OSI Approved :: MIT License',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Topic :: Scientific/Engineering :: Astronomy',
    ],

    include = [
    'solarkat/solarkat-pipeline/solarkat.yaml',
    'solarkat/solarkat-pipeline/solarkat-cabs.yaml',
    ]
)